### ISSUE TITLE
Devise and multi tenancy

### ISSUE THREAD

**Issue by KillWolf** [dandrews/omniauth-okta#32]
Hey all, 

We are trying to implement Okta as an SSO for our application.

As other (closed) issues has mentioned, multi tenancy for Okta requires us to host our users credentials. This pose a problem, as we setup what Okta does through an initializer, hence we only have one set of credentials. We need to dynamically change these as users access our app through the Okta SSO button. 

The closed issues mention you can use a SETUP_PROC to dynamically change the credentials, but in our case, this will not be possible. 

We use Devise, so using `Rails.application.config.middleware.use OmniAuth::Builder do`  will result in a frozen array issue.

Maybe I am missing an obvious way of solving this?

**Comment by stramec** [comment]
Hi appreciate this is closed, but did you find a solution, I'm in the same boat. Multi Tenancy seems an obvious use case, but finding a usable solution with Devise is proving a slog. Any help/tips appreciated.
